[project]
name = "my-analysis-tmpsf"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "hvplot>=0.12.2",
    "netcdf4>=1.7.4",
    "xarray>=2025.12.0",
]
